import Head from 'next/head';

import styles from '../styles/general.module.css';

import Audio from '@/components/Audio';
import Video from '@/components/Video';

import audio from '../data/dataAudio';
import video from '../data/dataVideo';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{ textAlign:'center', color:'red' }}>Multimedia</h1>
        <h3 style={{ textAlign: 'center', color: 'white' }}>Audio</h3>
      <div className={styles.container}>
        {
          audio.map(sonido => (
            <Audio 
              key={sonido.id}
              audio={...sonido}
            />
          ))
        }
      </div>
      <h3 style={{ textAlign: 'center', color: 'white' }}>Video</h3>
        <div className={styles.container}>
        {
          video.map(reproductor => (
            <Video 
              key={reproductor.id}
              video={...reproductor}
            />
          ))
        }
        </div>
    </>
  )
}
